# Generated by Django 3.2.4 on 2021-07-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('paid', models.BooleanField()),
                ('city', models.CharField(max_length=32)),
            ],
        ),
    ]
